### ISSUE TITLE
Torch not compiled with CUDA enabled. ComfyUI doesn't opening, how can I uninstall the whole thing so it will open again?

### ISSUE THREAD

**Issue by aiscapeadam** [LarryJane491/Lora-Training-in-Comfy#51]
Deleting from folders obviously didn't work. I want to uninstall but I don't know how, please help!

**Comment by Ma9hraby** [comment]
why did you delete anything? all you had to do is run update_comfyui.bat and update_comfyui_and_python_dependencies in the comfyui/update directory and they'll redownload the pytorch version compatible with CUDA allocation

that solved the issue with me, you could also browse the directory of python_embedding and cmd it to run a command, but the above method is easier @aiscapeadam

**Comment by dcastleproject** [comment]
> why did you delete anything? all you had to do is run update_comfyui.bat and update_comfyui_and_python_dependencies in the comfyui/update directory and they'll redownload the pytorch version compatible with CUDA allocation
> 
> that solved the issue with me, you could also browse the directory of python_embedding and cmd it to run a command, but the above method is easier @aiscapeadam

this worked for me, thanks

**Comment by Ma9hraby** [comment]
Hey, thank you so much ❤️
________________________________

**Comment by TemporalLabsLLC-SOL** [comment]
I ran into some conflicts when having the OG windows build and the "New" one that caused some conflicts when attempting this. Cleaning it out fixed it. Just for those who may run into a similar situation to consider.

**Comment by GeekyGhost** [comment]
A trick I started doing is keeping a spare copy of the portable lib folder incase I need to copy and paste torch back over to fix some craziness lol. Easiest way I've found to fix it when torch or something like that gets borked.
